from cleanstack.exceptions import DomainError


class CustomError(DomainError):
    pass
